### ISSUE TITLE
different hardware

### ISSUE THREAD

**Issue by niksimms** [arbox0/MedtronicUploader#1]
do you think it would be possible to use this dongle instead
http://www.hobbytronics.co.uk/wixel-usb-wireless-module
same TI chipset

**Comment by arbox0** [comment]
Wow, I don't know, from my point of view yes (perhaps we must change the USB device list to recognize this device...but that shouldn't be a problem), because I read info from a serial port. But You should ask this to JBerian in the mmcommander repository. Here: https://github.com/jberian/mmcommander

I think that the question is if you could program the chip with his binaries....

I am sorry, I can't give you a yes/no answer...

**Comment by MosiGitHub** [comment]
Even if this thread is closed: it has the wrong frequencies...
